language: python
python: '2.7'
before_install:
- sudo apt-get update -qq
- nvm install 7.3
- nvm use 7.3
install:
- pip install ansible
addons:
  sonarqube: true

script:
- ansible-playbook bbuddy.yml --inventory-file=host_travis_ci.txt --syntax-check
- ansible-playbook bbuddy.yml --inventory-file=host_travis_ci.txt
- bash -lec "npm install -g gulp-cli"
- bash -lec "npm install gulp --prefix $TRAVIS_BUILD_DIR/client -v"
- bash -lec "npm install --prefix $TRAVIS_BUILD_DIR/client -v"
- bash -lec "gulp mocha --cwd $TRAVIS_BUILD_DIR/client -v"
- bash -lec "gradle sonar -v"
- bash -lec "sonar-scanner"

notifications:
  slack: odd-e:fJq94ra1d8PFp66luNXdcBFs
