language: python
python: '2.7'
before_install:
- sudo apt-get update -qq
- nvm install 6.1
- nvm use 6.1
install:
- pip install ansible
- npm install -g gulp-cli gulp
addons:
  sonarqube: true

script:
- ansible-playbook bbuddy.yml --inventory-file=host_travis_ci.txt --syntax-check
- ansible-playbook bbuddy.yml --inventory-file=host_travis_ci.txt
- bash -lec "npm install --prefix ./client"
- bash -lec "gradle sonar"
- bash -lec "sonar-scanner"

notifications:
  slack: odd-e:fJq94ra1d8PFp66luNXdcBFs
